function [data_name, locations, pref_class, ok] = HPZ_Screen_Data_Set_Adding(data_name)

% this function is called from HPZ_Data_Set_Selection only. when the user
% browses for a new data file and chooses her desired file, this screen
% pops up and ask the user to define the name of the dataset (how it will
% appear on the HPZ_Data_Set_Selection screen), the column number that
% represent the required fields for the program, and the preferences class.

% for detailed explanations about input/output variables that possess
% the same name and meaning in multiple functions (e.g. data, action_flag, 
% pref_class, etc.) see: HPZ_Variables_Documentation in the "Others" sub-folder 

% it is recommended to use the numeric variables in the beginning of the 
% function when making changes to the screen.
% it is also recommended to use numeric variables in the same manner when
% adding new elements to the screen.



% the following initializations are only to prevent an error when the user
% presses "cancel":
pref_class = 0;
locations = 0;



% screen size
figure_width = 510;
figure_height = 460;
% limit of height as percentage of computer screen height
max_height_percent = HPZ_Constants.max_height_percent;

% height of bottom space designated for OK and Cancel buttons
buttons_space_height = 50;
% buttons height as percentage of the space they are in
buttons_height = 0.6;
% the distant between a button to the edge of the screen,
% and is also half the distance between buttons.
% the size of the buttons is designed to fit this and the buttons_height 
% and the width of the screen
buttons_dists = 10;
% number of buttons
buttons_num = 2;

% distance of highest element from top
top_dist = 10;
% distance of most left element from the left edge
left_dist = 20;

% how much distance between parts that are one next to each other (horizontally)  
move_right = 10;
% how much distance between parts that are one below each other 
move_down = 30;

% width of each element
element_width = 70;
label_height = 30;
text_height = 25;



%% create the figure, with a slider if needed
% scroll bar width (if scroll is needed)
scroll_width = 20;
bottom_space_height = buttons_space_height;
top_space_height = 0;
panel_height = figure_height - bottom_space_height - top_space_height;
figure_title = 'File Format Window';
[S.fh , S.panel] = ui_scroll_screen(figure_width, figure_height, scroll_width, max_height_percent, top_space_height, bottom_space_height, figure_title);

% width including scroll bar if there is one
pos = get(S.fh,'position');
full_width = pos(3);





%% Main Header
% current height of element
current_height = 20;
% current bottom coordinate
current_bottom = panel_height-top_dist - current_height;
S.main_label = uicontrol('Parent',S.panel, ...
    'style','text',...
    'units','pix',...
    'position',[0 , current_bottom , figure_width , current_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',12,'fontweight','bold',...
    'HorizontalAlignment','center',...
    'string','File Format Window');



%% Name of File Data

% current bottom coordinate
current_bottom = current_bottom - move_down;

% current height of element
current_height = 20;
% current bottom coordinate
current_bottom = current_bottom - current_height;
S.data_file_label = uicontrol('Parent',S.panel, ...
    'style','text',...
    'units','pix',...
    'position',[figure_width/8 , current_bottom , figure_width*3/4 , current_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',10,...
    'HorizontalAlignment','center',...
    'string','Name of Data File');

% current height of element
current_height = 30;
% current bottom coordinate
current_bottom = current_bottom - current_height;
S.data_file_text = uicontrol('Parent',S.panel, ...
    'style','edit',...
    'enable','off',...
    'string',data_name,...
    'units','pix',...
    'position',[figure_width/8 , current_bottom , figure_width*3/4 , current_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',10);



%% Name of Data

% current bottom coordinate
current_bottom = current_bottom - move_down/2;

% current height of element
current_height = 20;
% current bottom coordinate
current_bottom = current_bottom - current_height;
S.data_name_label = uicontrol('Parent',S.panel, ...
    'style','text',...
    'units','pix',...
    'position',[figure_width/8 , current_bottom , figure_width*3/4 , current_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',10,...
    'HorizontalAlignment','center',...
    'string','Name of Data');

% current height of element
current_height = 30;
% current bottom coordinate
current_bottom = current_bottom - current_height;
S.data_name_text = uicontrol('Parent',S.panel, ...
    'style','edit',...
    'string',data_name,...
    'enable', 'on', ...
    'units','pix',...
    'position',[figure_width/8 , current_bottom , figure_width*3/4 , current_height],...
    'backgroundc','white',...
    'fontsize',10);



%% Data Formatting Information

% current bottom coordinate (HOUTMAN-MAX is just below VARIAN)
current_bottom = current_bottom - move_down;

%% Labels
% current bottom and left coordinate
current_bottom = current_bottom - label_height;
current_left = left_dist;
S.subject_label = uicontrol('Parent',S.panel, ...
    'style','text',...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , label_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',8,...
    'HorizontalAlignment','center',...
    'string','Subject Column No.');

% current left coordinate
current_left = current_left + element_width + move_right;
S.observation_label = uicontrol('Parent',S.panel, ...
    'style','text',...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , label_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',8,...
    'HorizontalAlignment','center',...
    'string','Observation Column No.');

% current left coordinate
current_left = current_left + element_width + move_right;
S.quantity1_label = uicontrol('Parent',S.panel, ...
    'style','text',...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , label_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',8,...
    'HorizontalAlignment','center',...
    'string','Quantity 1 Column No.');

% current left coordinate
current_left = current_left + element_width + move_right;
S.quantity2_label = uicontrol('Parent',S.panel, ...
    'style','text',...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , label_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',8,...
    'HorizontalAlignment','center',...
    'string','Quantity 2 Column No.');

% current left coordinate
current_left = current_left + element_width + move_right;
S.maxquantity1_label = uicontrol('Parent',S.panel, ...
    'style','text',...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , label_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',8,...
    'HorizontalAlignment','center',...
    'string','MaxQuantity 1 Column No.');

% current left coordinate
current_left = current_left + element_width + move_right;
S.maxquantity2_label = uicontrol('Parent',S.panel, ...
    'style','text',...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , label_height],...
    'backgroundc',get(S.fh,'color'),...
    'fontsize',8,...
    'HorizontalAlignment','center',...
    'string','MaxQuantity 2 Column No.');

%% Texts to be editted by the user
% current bottom coordinate
current_bottom = current_bottom - text_height;
% current left coordinate
current_left = left_dist;
S.subject_text = uicontrol('Parent',S.panel, ...
    'style','edit',...
    'string','1',...
    'enable', 'on', ...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , text_height],...
    'backgroundc','white',...
    'fontsize',10);

% current left coordinate
current_left = current_left + element_width + move_right;
S.observation_text = uicontrol('Parent',S.panel, ...
    'style','edit',...
    'string','2',...
    'enable', 'on', ...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , text_height],...
    'backgroundc','white',...
    'fontsize',10);

% current left coordinate
current_left = current_left + element_width + move_right;
S.quantity1_text = uicontrol('Parent',S.panel, ...
    'style','edit',...
    'string','3',...
    'enable', 'on', ...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , text_height],...
    'backgroundc','white',...
    'fontsize',10);

% current left coordinate
current_left = current_left + element_width + move_right;
S.quantity2_text = uicontrol('Parent',S.panel, ...
    'style','edit',...
    'string','4',...
    'enable', 'on', ...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , text_height],...
    'backgroundc','white',...
    'fontsize',10);

% current left coordinate
current_left = current_left + element_width + move_right;
S.maxquantity1_text = uicontrol('Parent',S.panel, ...
    'style','edit',...
    'string','5',...
    'enable', 'on', ...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , text_height],...
    'backgroundc','white',...
    'fontsize',10);

% current left coordinate
current_left = current_left + element_width + move_right;
S.maxquantity2_text = uicontrol('Parent',S.panel, ...
    'style','edit',...
    'string','6',...
    'enable', 'on', ...
    'units','pix',...
    'position',[current_left , current_bottom , element_width , text_height],...
    'backgroundc','white',...
    'fontsize',10);



%% Preferences Class (Risk or OR)

% current bottom coordinate (HOUTMAN-MAX is just below VARIAN)
current_bottom = current_bottom - move_down;

% current height of element
current_height = 65;
% current bottom coordinate
current_bottom = current_bottom - current_height;
S.pref_class = uibuttongroup('Parent',S.panel, ...
    'units','pix',...
    'title', 'Preferences Class', ...
    'pos',[figure_width/8 , current_bottom , figure_width*3/4 , current_height]);

S.pref_class_rd(1) = uicontrol(S.pref_class,...
    'value', 1,...
    'enable','on',...
    'style','rad',...
    'unit','pix',...
    'position',[30 , 10 , figure_width*3/8 , 30],...
    'string','Risk  (Disappointment Aversion)');

S.pref_class_rd(2) = uicontrol(S.pref_class,...
    'value', 0,...
    'enable','on',...
    'style','rad',...
    'unit','pix',...
    'position',[30+figure_width*3/8 , 10 , figure_width*3/8 , 30],...
    'string','OR  (Other Regarding)');





%% OK Button
S.ok_button = uicontrol('Parent',S.fh, 'style','push',...
    'unit','pix',...
    'position',[buttons_dists , (1-buttons_height)/2*buttons_space_height , (full_width-(buttons_num+1)*buttons_dists)/buttons_num , buttons_height*buttons_space_height],...
    'string','OK',...
    'callback',{@ok_button_call,S});

%% Cancel Button
S.cancel_button = uicontrol('Parent',S.fh, 'style','push',...
    'unit','pix',...
    'position',[(full_width/2)+buttons_dists , (1-buttons_height)/2*buttons_space_height , (full_width-(buttons_num+1)*buttons_dists)/buttons_num , buttons_height*buttons_space_height],...
    'string','Cancel',...
    'callback',{@cancel_button_call,S});





uiwait(S.fh)  % Prevent all other processes from starting until closed.





%% OK button
function [] = ok_button_call(varargin)
    
    ok = 1;
    locations = [str2num(get(S.subject_text, 'string')),...
                str2num(get(S.observation_text, 'string')),...
                str2num(get(S.quantity1_text, 'string')),...
                str2num(get(S.quantity2_text, 'string')),...
                str2num(get(S.maxquantity1_text, 'string')),...
                str2num(get(S.maxquantity2_text, 'string'))]; %#ok<ST2NM>
    data_name = get(S.data_name_text, 'string');
    
    % preferences class
    if get(S.pref_class_rd(1), 'value') == 1.0
        pref_class = HPZ_Constants.risk_pref;
    elseif get(S.pref_class_rd(2), 'value') == 1.0
        pref_class = HPZ_Constants.OR_pref;
    else
        pref_class = 0;
    end

    % close the window
    close(S.fh);

end % end of call back function



%% Cancel button
function [] = cancel_button_call(varargin)
    % Callback for Cancel button.

    ok = 0;
    locations = 0;

    % close the window
    close(S.fh);

end

end
